<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <h1> "User id:${id}!"></h1><br>
        <h1> "Hello,${email}!"></h1>
    </div>
    <div class="row">
        <a href="/logout">Logout</a>
    </div>
</div>
<script src="/static/js/bootstrap.min.js"></script>
</body>
</html>