<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <h1> "Account id:${accountId}!"></h1><br>
        <h1> "Account name:${accountName}!"></h1><br>
        <h1> "Account value:${accountValue}!"></h1>
    </div>
</div>
<script src="/static/js/bootstrap.min.js"></script>
</body>
</html>